# Generated by Django 4.0.3 on 2022-10-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales_Person',
            new_name='SalesPerson',
        ),
    ]
