# Generated by Django 4.0.3 on 2022-10-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_sales_person_salesperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='imported_href',
            new_name='import_href',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='imported_id',
        ),
    ]
