# Generated by Django 4.0.3 on 2022-10-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_salesrecord_automobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales_rest.customer'),
        ),
    ]
